In [1]:
import psycopg2
conn = psycopg2.connect("host=db dbname=postgres user=postgres password=postgres")

In [8]:
import pandas as pd
df = pd.read_json('dataset/schema.md')

In [6]:
df.head(15)

,version,launch,longitude,latitude,height_km,velocity_kms,spaceTrack
type,String,UUID,Number,Number,Number,Number,NaN
default,None,None,None,None,None,None,NaN
ref,NaN,Launch,NaN,NaN,NaN,NaN,NaN
CCSDS_OMM_VERS,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
COMMENT,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
CREATION_DATE,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
ORIGINATOR,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
OBJECT_NAME,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
OBJECT_ID,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
CENTER_NAME,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
REF_FRAME,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
TIME_SYSTEM,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
MEAN_ELEMENT_THEORY,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
EPOCH,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'String', 'default': None}"
MEAN_MOTION,NaN,NaN,NaN,NaN,NaN,NaN,"{'type': 'Number', 'default': None}"

In [4]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:postgres@db:5432/postgres')

In [7]:
df.to_sql('starlinkschema', engine)

df_pg = pd.read_sql_query('Select * from starlinkschema', con=engine)

df_pg.head()